/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eoy_project;

import java.io.File; 
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.Scanner; 
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;




/**
 *
 * @author 23038
 */
public class MonsterCardCatalogue extends javax.swing.JFrame {
    
    String cardList[][] = {
        {"NULL","14", "1", "1", "1", "1", "E"},
        {"NULL","14", "1", "1", "1", "1", "E"},
        {"NULL","14", "1", "1", "1", "1", "E"},
        {"NULL","14", "1", "1", "1", "1", "E"},
        {"NULL","14", "1", "1", "1", "1", "E"},
        {"NULL","14", "1", "1", "1", "1", "E"},
        {"NULL","14", "1", "1", "1", "1", "E"},
        {"NULL","14", "1", "1", "1", "1", "E"},
        {"NULL","14", "1", "1", "1", "1", "E"},
        {"NULL","14", "1", "1", "1", "1", "E"}
    };
    
    Icon imageList[] = {
        new ImageIcon ("src/EOY_project/Barkspike.png"), 
        new ImageIcon ("src/EOY_project/Blazegolem.png"), 
        new ImageIcon ("src/EOY_project/Clusters.png"),
        new ImageIcon ("src/EOY_project/Dawnmirage.png"),
        new ImageIcon ("src/EOY_project/Deca.png"),
        new ImageIcon ("src/EOY_project/Froststep.png"),
        new ImageIcon ("src/EOY_project/Moldvine.png"),
        new ImageIcon ("src/EOY_project/Placeholder.jpg"),
        new ImageIcon ("src/EOY_project/Planetary.png"),
        new ImageIcon ("src/EOY_project/Sandworm.png"),
        new ImageIcon ("src/EOY_project/Vexscream.png"),
        new ImageIcon ("src/EOY_project/Vortexwing.png"),
        new ImageIcon ("src/EOY_project/Winged.png"),
        new ImageIcon ("src/EOY_project/Wispghoul.png"),
        new ImageIcon ("src/EOY_project/Placeholder.jpg")
    };
    
    
    
    // jobj.setIcon(name);
    

    
    String name;
    int image;
    int strength;
    int speed;
    int stealth;
    int cunning;
    String cardType;
    int STATCAPMIN;
    int STATCAPMAX;
    int cardTotalStats;
    boolean confirmCard;
    String sortMethod;
    String cardToSearch;
    
    // temp variables
    int lineCount;
    
    

    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MonsterCardCatalogue.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public MonsterCardCatalogue() {
        // declare
        STATCAPMIN = 1;
        STATCAPMAX = 25;
        lineCount = 0;

        File monsterCataloguetxt = new File("src/EOY_project/cardListTextFile.txt");
        
        try(Scanner fileReader = new Scanner(monsterCataloguetxt)) {
            while(fileReader.hasNextLine()) {        
                String line = fileReader.nextLine();
                String[] getLine = line.split(",");
                System.out.println(Arrays.toString(getLine));
                cardList[lineCount] = (getLine);
                lineCount++;
            }
            
            System.out.println(Arrays.deepToString(cardList));
        } catch(FileNotFoundException e) {
             System.out.println(e);
        }
        
//        System.out.println(Arrays.deepToString(cardList));
        
        initComponents();
        cardRender();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlParentPanel = new javax.swing.JPanel();
        pnlHomePanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnTextFileOutput = new javax.swing.JButton();
        btnQuitButton = new javax.swing.JButton();
        btnSearchButton = new javax.swing.JButton();
        btnCreateButton = new javax.swing.JButton();
        btnDeleteButton = new javax.swing.JButton();
        pnlCard1 = new javax.swing.JPanel();
        lblCardImage1 = new javax.swing.JLabel();
        lblCardName1 = new javax.swing.JLabel();
        lblCardStrength1 = new javax.swing.JLabel();
        lblCardSpeed1 = new javax.swing.JLabel();
        lblCardStealth1 = new javax.swing.JLabel();
        lblCardCunning1 = new javax.swing.JLabel();
        pnlCard2 = new javax.swing.JPanel();
        lblCardImage2 = new javax.swing.JLabel();
        lblCardName2 = new javax.swing.JLabel();
        lblCardStrength2 = new javax.swing.JLabel();
        lblCardSpeed2 = new javax.swing.JLabel();
        lblCardStealth2 = new javax.swing.JLabel();
        lblCardCunning2 = new javax.swing.JLabel();
        pnlCard3 = new javax.swing.JPanel();
        lblCardImage3 = new javax.swing.JLabel();
        lblCardName3 = new javax.swing.JLabel();
        lblCardStrength3 = new javax.swing.JLabel();
        lblCardSpeed3 = new javax.swing.JLabel();
        lblCardStealth3 = new javax.swing.JLabel();
        lblCardCunning3 = new javax.swing.JLabel();
        pnlCard4 = new javax.swing.JPanel();
        lblCardImage4 = new javax.swing.JLabel();
        lblCardName4 = new javax.swing.JLabel();
        lblCardStrength4 = new javax.swing.JLabel();
        lblCardSpeed4 = new javax.swing.JLabel();
        lblCardStealth4 = new javax.swing.JLabel();
        lblCardCunning4 = new javax.swing.JLabel();
        pnlCard5 = new javax.swing.JPanel();
        lblCardImage5 = new javax.swing.JLabel();
        lblCardName5 = new javax.swing.JLabel();
        lblCardStrength5 = new javax.swing.JLabel();
        lblCardSpeed5 = new javax.swing.JLabel();
        lblCardStealth5 = new javax.swing.JLabel();
        lblCardCunning5 = new javax.swing.JLabel();
        pnlCard6 = new javax.swing.JPanel();
        lblCardImage6 = new javax.swing.JLabel();
        lblCardName6 = new javax.swing.JLabel();
        lblCardStrength6 = new javax.swing.JLabel();
        lblCardSpeed6 = new javax.swing.JLabel();
        lblCardStealth6 = new javax.swing.JLabel();
        lblCardCunning6 = new javax.swing.JLabel();
        pnlCard7 = new javax.swing.JPanel();
        lblCardImage7 = new javax.swing.JLabel();
        lblCardName7 = new javax.swing.JLabel();
        lblCardStrength7 = new javax.swing.JLabel();
        lblCardSpeed7 = new javax.swing.JLabel();
        lblCardStealth7 = new javax.swing.JLabel();
        lblCardCunning7 = new javax.swing.JLabel();
        pnlCard8 = new javax.swing.JPanel();
        lblCardImage8 = new javax.swing.JLabel();
        lblCardName8 = new javax.swing.JLabel();
        lblCardStrength8 = new javax.swing.JLabel();
        lblCardSpeed8 = new javax.swing.JLabel();
        lblCardStealth8 = new javax.swing.JLabel();
        lblCardCunning8 = new javax.swing.JLabel();
        pnlCard9 = new javax.swing.JPanel();
        lblCardImage9 = new javax.swing.JLabel();
        lblCardName9 = new javax.swing.JLabel();
        lblCardStrength9 = new javax.swing.JLabel();
        lblCardSpeed9 = new javax.swing.JLabel();
        lblCardStealth9 = new javax.swing.JLabel();
        lblCardCunning9 = new javax.swing.JLabel();
        pnlCard10 = new javax.swing.JPanel();
        lblCardImage10 = new javax.swing.JLabel();
        lblCardName10 = new javax.swing.JLabel();
        lblCardStrength10 = new javax.swing.JLabel();
        lblCardSpeed10 = new javax.swing.JLabel();
        lblCardStealth10 = new javax.swing.JLabel();
        lblCardCunning10 = new javax.swing.JLabel();
        pnlCreatePanel = new javax.swing.JPanel();
        pnlCreatedCard = new javax.swing.JPanel();
        lblCardImageCreated = new javax.swing.JLabel();
        lblCardNameCreated = new javax.swing.JLabel();
        lblCardStrengthCreated = new javax.swing.JLabel();
        lblCardSpeedCreated = new javax.swing.JLabel();
        lblCardStealthCreated = new javax.swing.JLabel();
        lblCardCunningCreated = new javax.swing.JLabel();
        lblCreateTitle = new javax.swing.JLabel();
        lblCreateCard = new javax.swing.JLabel();
        txtCreateCardNameEntry = new javax.swing.JTextField();
        lblStrengthValue = new javax.swing.JLabel();
        lblSpeedValue = new javax.swing.JLabel();
        lblStealthValue = new javax.swing.JLabel();
        lblCunningValue = new javax.swing.JLabel();
        txtStrengthInput = new javax.swing.JTextField();
        txtSpeedInput = new javax.swing.JTextField();
        txtStealthInput = new javax.swing.JTextField();
        txtCunningInput = new javax.swing.JTextField();
        btnRenderCard = new javax.swing.JButton();
        btnQuitCreate = new javax.swing.JButton();
        btnDiscardCard = new javax.swing.JButton();
        lblImageToChoose = new javax.swing.JLabel();
        txtImageInput = new javax.swing.JTextField();
        btnCreateCard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 231, 194));

        pnlParentPanel.setFocusTraversalPolicyProvider(true);
        pnlParentPanel.setLayout(new java.awt.CardLayout());

        pnlHomePanel.setBackground(new java.awt.Color(255, 231, 194));
        pnlHomePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 235, 153), 12));

        lblTitle.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        lblTitle.setText("Monster Card Catalogue");

        btnTextFileOutput.setBackground(new java.awt.Color(204, 163, 0));
        btnTextFileOutput.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btnTextFileOutput.setForeground(new java.awt.Color(255, 255, 255));
        btnTextFileOutput.setText("Text File Output");
        btnTextFileOutput.addActionListener(this::btnTextFileOutputActionPerformed);

        btnQuitButton.setBackground(new java.awt.Color(204, 0, 0));
        btnQuitButton.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnQuitButton.setForeground(new java.awt.Color(255, 255, 255));
        btnQuitButton.setText("Quit");
        btnQuitButton.addActionListener(this::btnQuitButtonActionPerformed);

        btnSearchButton.setBackground(new java.awt.Color(0, 37, 204));
        btnSearchButton.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnSearchButton.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchButton.setText("Search");
        btnSearchButton.addActionListener(this::btnSearchButtonActionPerformed);

        btnCreateButton.setBackground(new java.awt.Color(126, 217, 87));
        btnCreateButton.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnCreateButton.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateButton.setText("Create");
        btnCreateButton.addActionListener(this::btnCreateButtonActionPerformed);

        btnDeleteButton.setBackground(new java.awt.Color(255, 49, 49));
        btnDeleteButton.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnDeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteButton.setText("Delete");
        btnDeleteButton.addActionListener(this::btnDeleteButtonActionPerformed);

        pnlCard1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eoy_project/placeholder.jpg"))); // NOI18N
        lblCardImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardName1.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardName1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardName1.setText("[Name]");

        lblCardStrength1.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStrength1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStrength1.setText("STR:25");

        lblCardSpeed1.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardSpeed1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardSpeed1.setText("SPD:25");

        lblCardStealth1.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStealth1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStealth1.setText("STH:25");

        lblCardCunning1.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardCunning1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardCunning1.setText("CNG:25");

        javax.swing.GroupLayout pnlCard1Layout = new javax.swing.GroupLayout(pnlCard1);
        pnlCard1.setLayout(pnlCard1Layout);
        pnlCard1Layout.setHorizontalGroup(
            pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard1Layout.createSequentialGroup()
                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCard1Layout.createSequentialGroup()
                        .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblCardName1))
                            .addGroup(pnlCard1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblCardImage1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCard1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard1Layout.createSequentialGroup()
                                .addComponent(lblCardStrength1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCardSpeed1))
                            .addGroup(pnlCard1Layout.createSequentialGroup()
                                .addComponent(lblCardStealth1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(lblCardCunning1)))))
                .addContainerGap())
        );
        pnlCard1Layout.setVerticalGroup(
            pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblCardImage1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCardName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStrength1)
                    .addComponent(lblCardSpeed1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStealth1)
                    .addComponent(lblCardCunning1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlCard2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eoy_project/placeholder.jpg"))); // NOI18N
        lblCardImage2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardName2.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardName2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardName2.setText("[Name]");

        lblCardStrength2.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStrength2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStrength2.setText("STR:25");

        lblCardSpeed2.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardSpeed2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardSpeed2.setText("SPD:25");

        lblCardStealth2.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStealth2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStealth2.setText("STH:25");

        lblCardCunning2.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardCunning2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardCunning2.setText("CNG:25");

        javax.swing.GroupLayout pnlCard2Layout = new javax.swing.GroupLayout(pnlCard2);
        pnlCard2.setLayout(pnlCard2Layout);
        pnlCard2Layout.setHorizontalGroup(
            pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard2Layout.createSequentialGroup()
                .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCard2Layout.createSequentialGroup()
                        .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblCardName2))
                            .addGroup(pnlCard2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblCardImage2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCard2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard2Layout.createSequentialGroup()
                                .addComponent(lblCardStrength2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCardSpeed2))
                            .addGroup(pnlCard2Layout.createSequentialGroup()
                                .addComponent(lblCardStealth2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(lblCardCunning2)))))
                .addContainerGap())
        );
        pnlCard2Layout.setVerticalGroup(
            pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblCardImage2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCardName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStrength2)
                    .addComponent(lblCardSpeed2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStealth2)
                    .addComponent(lblCardCunning2))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlCard3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eoy_project/placeholder.jpg"))); // NOI18N
        lblCardImage3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardName3.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardName3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardName3.setText("[Name]");

        lblCardStrength3.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStrength3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStrength3.setText("STR:25");

        lblCardSpeed3.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardSpeed3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardSpeed3.setText("SPD:25");

        lblCardStealth3.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStealth3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStealth3.setText("STH:25");

        lblCardCunning3.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardCunning3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardCunning3.setText("CNG:25");

        javax.swing.GroupLayout pnlCard3Layout = new javax.swing.GroupLayout(pnlCard3);
        pnlCard3.setLayout(pnlCard3Layout);
        pnlCard3Layout.setHorizontalGroup(
            pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard3Layout.createSequentialGroup()
                .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCard3Layout.createSequentialGroup()
                        .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard3Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblCardName3))
                            .addGroup(pnlCard3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblCardImage3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCard3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard3Layout.createSequentialGroup()
                                .addComponent(lblCardStrength3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCardSpeed3))
                            .addGroup(pnlCard3Layout.createSequentialGroup()
                                .addComponent(lblCardStealth3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(lblCardCunning3)))))
                .addContainerGap())
        );
        pnlCard3Layout.setVerticalGroup(
            pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblCardImage3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCardName3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStrength3)
                    .addComponent(lblCardSpeed3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStealth3)
                    .addComponent(lblCardCunning3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlCard4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eoy_project/placeholder.jpg"))); // NOI18N
        lblCardImage4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardName4.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardName4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardName4.setText("[Name]");

        lblCardStrength4.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStrength4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStrength4.setText("STR:25");

        lblCardSpeed4.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardSpeed4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardSpeed4.setText("SPD:25");

        lblCardStealth4.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStealth4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStealth4.setText("STH:25");

        lblCardCunning4.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardCunning4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardCunning4.setText("CNG:25");

        javax.swing.GroupLayout pnlCard4Layout = new javax.swing.GroupLayout(pnlCard4);
        pnlCard4.setLayout(pnlCard4Layout);
        pnlCard4Layout.setHorizontalGroup(
            pnlCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard4Layout.createSequentialGroup()
                .addGroup(pnlCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCard4Layout.createSequentialGroup()
                        .addGroup(pnlCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard4Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblCardName4))
                            .addGroup(pnlCard4Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblCardImage4)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCard4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard4Layout.createSequentialGroup()
                                .addComponent(lblCardStrength4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCardSpeed4))
                            .addGroup(pnlCard4Layout.createSequentialGroup()
                                .addComponent(lblCardStealth4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(lblCardCunning4)))))
                .addContainerGap())
        );
        pnlCard4Layout.setVerticalGroup(
            pnlCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblCardImage4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCardName4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStrength4)
                    .addComponent(lblCardSpeed4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStealth4)
                    .addComponent(lblCardCunning4))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlCard5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eoy_project/placeholder.jpg"))); // NOI18N
        lblCardImage5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardName5.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardName5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardName5.setText("[Name]");

        lblCardStrength5.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStrength5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStrength5.setText("STR:25");

        lblCardSpeed5.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardSpeed5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardSpeed5.setText("SPD:25");

        lblCardStealth5.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStealth5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStealth5.setText("STH:25");

        lblCardCunning5.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardCunning5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardCunning5.setText("CNG:25");

        javax.swing.GroupLayout pnlCard5Layout = new javax.swing.GroupLayout(pnlCard5);
        pnlCard5.setLayout(pnlCard5Layout);
        pnlCard5Layout.setHorizontalGroup(
            pnlCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard5Layout.createSequentialGroup()
                .addGroup(pnlCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCard5Layout.createSequentialGroup()
                        .addGroup(pnlCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard5Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblCardName5))
                            .addGroup(pnlCard5Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblCardImage5)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCard5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard5Layout.createSequentialGroup()
                                .addComponent(lblCardStrength5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCardSpeed5))
                            .addGroup(pnlCard5Layout.createSequentialGroup()
                                .addComponent(lblCardStealth5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(lblCardCunning5)))))
                .addContainerGap())
        );
        pnlCard5Layout.setVerticalGroup(
            pnlCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblCardImage5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCardName5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStrength5)
                    .addComponent(lblCardSpeed5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStealth5)
                    .addComponent(lblCardCunning5))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlCard6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardImage6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eoy_project/placeholder.jpg"))); // NOI18N
        lblCardImage6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardName6.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardName6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardName6.setText("[Name]");

        lblCardStrength6.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStrength6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStrength6.setText("STR:25");

        lblCardSpeed6.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardSpeed6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardSpeed6.setText("SPD:25");

        lblCardStealth6.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStealth6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStealth6.setText("STH:25");

        lblCardCunning6.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardCunning6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardCunning6.setText("CNG:25");

        javax.swing.GroupLayout pnlCard6Layout = new javax.swing.GroupLayout(pnlCard6);
        pnlCard6.setLayout(pnlCard6Layout);
        pnlCard6Layout.setHorizontalGroup(
            pnlCard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard6Layout.createSequentialGroup()
                .addGroup(pnlCard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCard6Layout.createSequentialGroup()
                        .addGroup(pnlCard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard6Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblCardName6))
                            .addGroup(pnlCard6Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblCardImage6)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCard6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard6Layout.createSequentialGroup()
                                .addComponent(lblCardStrength6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCardSpeed6))
                            .addGroup(pnlCard6Layout.createSequentialGroup()
                                .addComponent(lblCardStealth6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(lblCardCunning6)))))
                .addContainerGap())
        );
        pnlCard6Layout.setVerticalGroup(
            pnlCard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblCardImage6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCardName6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStrength6)
                    .addComponent(lblCardSpeed6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStealth6)
                    .addComponent(lblCardCunning6))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlCard7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eoy_project/placeholder.jpg"))); // NOI18N
        lblCardImage7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardName7.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardName7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardName7.setText("[Name]");

        lblCardStrength7.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStrength7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStrength7.setText("STR:25");

        lblCardSpeed7.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardSpeed7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardSpeed7.setText("SPD:25");

        lblCardStealth7.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStealth7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStealth7.setText("STH:25");

        lblCardCunning7.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardCunning7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardCunning7.setText("CNG:25");

        javax.swing.GroupLayout pnlCard7Layout = new javax.swing.GroupLayout(pnlCard7);
        pnlCard7.setLayout(pnlCard7Layout);
        pnlCard7Layout.setHorizontalGroup(
            pnlCard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard7Layout.createSequentialGroup()
                .addGroup(pnlCard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCard7Layout.createSequentialGroup()
                        .addGroup(pnlCard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard7Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblCardName7))
                            .addGroup(pnlCard7Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblCardImage7)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCard7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard7Layout.createSequentialGroup()
                                .addComponent(lblCardStrength7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCardSpeed7))
                            .addGroup(pnlCard7Layout.createSequentialGroup()
                                .addComponent(lblCardStealth7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(lblCardCunning7)))))
                .addContainerGap())
        );
        pnlCard7Layout.setVerticalGroup(
            pnlCard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard7Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblCardImage7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCardName7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStrength7)
                    .addComponent(lblCardSpeed7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStealth7)
                    .addComponent(lblCardCunning7))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlCard8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardImage8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eoy_project/placeholder.jpg"))); // NOI18N
        lblCardImage8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardName8.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardName8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardName8.setText("[Name]");

        lblCardStrength8.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStrength8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStrength8.setText("STR:25");

        lblCardSpeed8.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardSpeed8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardSpeed8.setText("SPD:25");

        lblCardStealth8.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStealth8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStealth8.setText("STH:25");

        lblCardCunning8.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardCunning8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardCunning8.setText("CNG:25");

        javax.swing.GroupLayout pnlCard8Layout = new javax.swing.GroupLayout(pnlCard8);
        pnlCard8.setLayout(pnlCard8Layout);
        pnlCard8Layout.setHorizontalGroup(
            pnlCard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard8Layout.createSequentialGroup()
                .addGroup(pnlCard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCard8Layout.createSequentialGroup()
                        .addGroup(pnlCard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard8Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblCardName8))
                            .addGroup(pnlCard8Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblCardImage8)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCard8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard8Layout.createSequentialGroup()
                                .addComponent(lblCardStrength8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCardSpeed8))
                            .addGroup(pnlCard8Layout.createSequentialGroup()
                                .addComponent(lblCardStealth8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(lblCardCunning8)))))
                .addContainerGap())
        );
        pnlCard8Layout.setVerticalGroup(
            pnlCard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard8Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblCardImage8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCardName8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStrength8)
                    .addComponent(lblCardSpeed8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStealth8)
                    .addComponent(lblCardCunning8))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlCard9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardImage9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eoy_project/placeholder.jpg"))); // NOI18N
        lblCardImage9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardName9.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardName9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardName9.setText("[Name]");

        lblCardStrength9.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStrength9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStrength9.setText("STR:25");

        lblCardSpeed9.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardSpeed9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardSpeed9.setText("SPD:25");

        lblCardStealth9.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStealth9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStealth9.setText("STH:25");

        lblCardCunning9.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardCunning9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardCunning9.setText("CNG:25");

        javax.swing.GroupLayout pnlCard9Layout = new javax.swing.GroupLayout(pnlCard9);
        pnlCard9.setLayout(pnlCard9Layout);
        pnlCard9Layout.setHorizontalGroup(
            pnlCard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard9Layout.createSequentialGroup()
                .addGroup(pnlCard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCard9Layout.createSequentialGroup()
                        .addGroup(pnlCard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard9Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblCardName9))
                            .addGroup(pnlCard9Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblCardImage9)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCard9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard9Layout.createSequentialGroup()
                                .addComponent(lblCardStrength9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCardSpeed9))
                            .addGroup(pnlCard9Layout.createSequentialGroup()
                                .addComponent(lblCardStealth9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(lblCardCunning9)))))
                .addContainerGap())
        );
        pnlCard9Layout.setVerticalGroup(
            pnlCard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard9Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblCardImage9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCardName9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStrength9)
                    .addComponent(lblCardSpeed9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStealth9)
                    .addComponent(lblCardCunning9))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlCard10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardImage10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eoy_project/placeholder.jpg"))); // NOI18N
        lblCardImage10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardName10.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardName10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardName10.setText("[Name]");

        lblCardStrength10.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStrength10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStrength10.setText("STR:25");

        lblCardSpeed10.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardSpeed10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardSpeed10.setText("SPD:25");

        lblCardStealth10.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStealth10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStealth10.setText("STH:25");

        lblCardCunning10.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardCunning10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardCunning10.setText("CNG:25");

        javax.swing.GroupLayout pnlCard10Layout = new javax.swing.GroupLayout(pnlCard10);
        pnlCard10.setLayout(pnlCard10Layout);
        pnlCard10Layout.setHorizontalGroup(
            pnlCard10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard10Layout.createSequentialGroup()
                .addGroup(pnlCard10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCard10Layout.createSequentialGroup()
                        .addGroup(pnlCard10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard10Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblCardName10))
                            .addGroup(pnlCard10Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblCardImage10)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCard10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCard10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard10Layout.createSequentialGroup()
                                .addComponent(lblCardStrength10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCardSpeed10))
                            .addGroup(pnlCard10Layout.createSequentialGroup()
                                .addComponent(lblCardStealth10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(lblCardCunning10)))))
                .addContainerGap())
        );
        pnlCard10Layout.setVerticalGroup(
            pnlCard10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard10Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblCardImage10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCardName10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCard10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStrength10)
                    .addComponent(lblCardSpeed10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCard10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStealth10)
                    .addComponent(lblCardCunning10))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlHomePanelLayout = new javax.swing.GroupLayout(pnlHomePanel);
        pnlHomePanel.setLayout(pnlHomePanelLayout);
        pnlHomePanelLayout.setHorizontalGroup(
            pnlHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomePanelLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(pnlHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomePanelLayout.createSequentialGroup()
                        .addComponent(btnDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnQuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))
                    .addGroup(pnlHomePanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnTextFileOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHomePanelLayout.createSequentialGroup()
                        .addComponent(pnlCard6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlCard7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlCard8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlCard9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlCard10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHomePanelLayout.createSequentialGroup()
                        .addComponent(pnlCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlCard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlCard3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlCard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlCard5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHomePanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblTitle)))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        pnlHomePanelLayout.setVerticalGroup(
            pnlHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(46, 46, 46)
                .addGroup(pnlHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCard3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCard5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCard6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCard7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCard8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCard9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCard10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTextFileOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlParentPanel.add(pnlHomePanel, "card2");

        pnlCreatePanel.setBackground(new java.awt.Color(255, 231, 194));
        pnlCreatePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 235, 153), 12));
        pnlCreatePanel.setForeground(new java.awt.Color(255, 231, 194));

        pnlCreatedCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardImageCreated.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eoy_project/placeholder.jpg"))); // NOI18N
        lblCardImageCreated.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblCardNameCreated.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardNameCreated.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardNameCreated.setText("[Name]");

        lblCardStrengthCreated.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStrengthCreated.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStrengthCreated.setText("STR:25");

        lblCardSpeedCreated.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardSpeedCreated.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardSpeedCreated.setText("SPD:25");

        lblCardStealthCreated.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardStealthCreated.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardStealthCreated.setText("STH:25");

        lblCardCunningCreated.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        lblCardCunningCreated.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCardCunningCreated.setText("CNG:25");

        javax.swing.GroupLayout pnlCreatedCardLayout = new javax.swing.GroupLayout(pnlCreatedCard);
        pnlCreatedCard.setLayout(pnlCreatedCardLayout);
        pnlCreatedCardLayout.setHorizontalGroup(
            pnlCreatedCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreatedCardLayout.createSequentialGroup()
                .addGroup(pnlCreatedCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCreatedCardLayout.createSequentialGroup()
                        .addGroup(pnlCreatedCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCreatedCardLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblCardNameCreated))
                            .addGroup(pnlCreatedCardLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblCardImageCreated)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCreatedCardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCreatedCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCreatedCardLayout.createSequentialGroup()
                                .addComponent(lblCardStrengthCreated)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCardSpeedCreated))
                            .addGroup(pnlCreatedCardLayout.createSequentialGroup()
                                .addComponent(lblCardStealthCreated)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(lblCardCunningCreated)))))
                .addContainerGap())
        );
        pnlCreatedCardLayout.setVerticalGroup(
            pnlCreatedCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreatedCardLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblCardImageCreated)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCardNameCreated)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCreatedCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStrengthCreated)
                    .addComponent(lblCardSpeedCreated))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCreatedCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardStealthCreated)
                    .addComponent(lblCardCunningCreated))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lblCreateTitle.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        lblCreateTitle.setText("Create A Card:");

        lblCreateCard.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        lblCreateCard.setText("Name:");

        txtCreateCardNameEntry.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        txtCreateCardNameEntry.setText("\"Name\"");
        txtCreateCardNameEntry.addActionListener(this::txtCreateCardNameEntryActionPerformed);

        lblStrengthValue.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        lblStrengthValue.setText("Strength:");

        lblSpeedValue.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        lblSpeedValue.setText("Speed:");

        lblStealthValue.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        lblStealthValue.setText("Stealth:");

        lblCunningValue.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        lblCunningValue.setText("Cunning:");

        txtStrengthInput.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        txtStrengthInput.setText("25");
        txtStrengthInput.setToolTipText("");
        txtStrengthInput.addActionListener(this::txtStrengthInputActionPerformed);

        txtSpeedInput.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        txtSpeedInput.setText("25");
        txtSpeedInput.setToolTipText("");
        txtSpeedInput.addActionListener(this::txtSpeedInputActionPerformed);

        txtStealthInput.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        txtStealthInput.setText("25");
        txtStealthInput.setToolTipText("");
        txtStealthInput.addActionListener(this::txtStealthInputActionPerformed);

        txtCunningInput.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        txtCunningInput.setText("25");
        txtCunningInput.setToolTipText("");
        txtCunningInput.addActionListener(this::txtCunningInputActionPerformed);

        btnRenderCard.setBackground(new java.awt.Color(126, 217, 87));
        btnRenderCard.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnRenderCard.setForeground(new java.awt.Color(255, 255, 255));
        btnRenderCard.setText("Render");
        btnRenderCard.addActionListener(this::btnRenderCardActionPerformed);

        btnQuitCreate.setBackground(new java.awt.Color(204, 0, 0));
        btnQuitCreate.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnQuitCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnQuitCreate.setText("Quit");
        btnQuitCreate.addActionListener(this::btnQuitCreateActionPerformed);

        btnDiscardCard.setBackground(new java.awt.Color(204, 163, 0));
        btnDiscardCard.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnDiscardCard.setForeground(new java.awt.Color(255, 255, 255));
        btnDiscardCard.setText("Discard");
        btnDiscardCard.addActionListener(this::btnDiscardCardActionPerformed);

        lblImageToChoose.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        lblImageToChoose.setText("Image:");

        txtImageInput.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        txtImageInput.setText("14");
        txtImageInput.setToolTipText("");
        txtImageInput.addActionListener(this::txtImageInputActionPerformed);

        btnCreateCard.setBackground(new java.awt.Color(126, 217, 87));
        btnCreateCard.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnCreateCard.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateCard.setText("Create");
        btnCreateCard.addActionListener(this::btnCreateCardActionPerformed);

        javax.swing.GroupLayout pnlCreatePanelLayout = new javax.swing.GroupLayout(pnlCreatePanel);
        pnlCreatePanel.setLayout(pnlCreatePanelLayout);
        pnlCreatePanelLayout.setHorizontalGroup(
            pnlCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreatePanelLayout.createSequentialGroup()
                .addGroup(pnlCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCreatePanelLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(lblCreateTitle))
                    .addGroup(pnlCreatePanelLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(pnlCreatedCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCreateCard)
                            .addComponent(lblStrengthValue)
                            .addComponent(lblSpeedValue)
                            .addComponent(lblStealthValue)
                            .addComponent(lblCunningValue)
                            .addComponent(lblImageToChoose))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCreateCardNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtImageInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStealthInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSpeedInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCunningInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStrengthInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCreatePanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(pnlCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCreateCard, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlCreatePanelLayout.createSequentialGroup()
                                .addComponent(btnRenderCard, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDiscardCard, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuitCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(437, Short.MAX_VALUE))
        );
        pnlCreatePanelLayout.setVerticalGroup(
            pnlCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreatePanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblCreateTitle)
                .addGap(18, 18, 18)
                .addGroup(pnlCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCreatePanelLayout.createSequentialGroup()
                        .addGroup(pnlCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCreateCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCreateCardNameEntry))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStrengthValue)
                            .addComponent(txtStrengthInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(pnlCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSpeedInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSpeedValue))
                        .addGap(5, 5, 5)
                        .addGroup(pnlCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtStealthInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStealthValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCunningValue)
                            .addComponent(txtCunningInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pnlCreatedCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImageToChoose)
                    .addComponent(txtImageInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlCreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRenderCard, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiscardCard, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuitCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCreateCard, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pnlParentPanel.add(pnlCreatePanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlParentPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>                        

    
    
    
    
    private void btnTextFileOutputActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        File monsterCataloguetxt = new File("src/EOY_project/cardListTextFile.txt");
        
        try(Scanner fileReader = new Scanner(monsterCataloguetxt)) {
            while(fileReader.hasNextLine()) {
                String line = fileReader.nextLine();
                System.out.println(line);
            }
        } catch(FileNotFoundException e) {
             System.out.println(e);
        }
       
        
    }                                                 

    private void btnQuitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        System.exit(0);
    }                                             

    private void btnSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void btnCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        pnlParentPanel.removeAll();
        pnlParentPanel.add(pnlCreatePanel);
        pnlParentPanel.repaint();
        pnlParentPanel.revalidate();
    }                                               

    private void btnDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void txtImageInputActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void btnDiscardCardActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void btnQuitCreateActionPerformed(java.awt.event.ActionEvent evt) {                                              
        System.exit(0);
    }                                             

    private void btnRenderCardActionPerformed(java.awt.event.ActionEvent evt) {                                              
        name = txtCreateCardNameEntry.getText();
        
        try {
            strength = Integer.parseInt(txtStrengthInput.getText());
            speed = Integer.parseInt(txtSpeedInput.getText());
            stealth = Integer.parseInt(txtStealthInput.getText());
            cunning = Integer.parseInt(txtCunningInput.getText());
            image = Integer.parseInt(txtImageInput.getText());
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Please input a numerical value for Strength, Speed, Stealth, Cunning and Image.","Invalid Value",JOptionPane.OK_CANCEL_OPTION);
            throw new IllegalArgumentException("String was inputted where an integer was expected.");
        }
        
        
        if (strength > STATCAPMAX || strength < STATCAPMIN || speed > STATCAPMAX || speed < STATCAPMIN || stealth > STATCAPMAX || stealth < STATCAPMIN || cunning > STATCAPMAX || cunning < STATCAPMIN ) {
            JOptionPane.showMessageDialog(null,"All card values must be kept between 1-25 for Strength, Speed, Stealth and Cunning.","Invalid Value",JOptionPane.OK_CANCEL_OPTION);
            throw new IllegalArgumentException("All stats must be between 1-25");
        } else if (0 > image || image > 14) {
            JOptionPane.showMessageDialog(null,"Image values span between 0 and 14.","Invalid Value",JOptionPane.OK_CANCEL_OPTION);
            throw new IllegalArgumentException("Image value must be between 0-14");
        }
        
        lblCardImageCreated.setIcon(imageList[image]);
        lblCardNameCreated.setText(name);
        lblCardStrengthCreated.setText("STR: " + String.valueOf(strength));
        lblCardSpeedCreated.setText("SPD: " + String.valueOf(speed));
        lblCardStealthCreated.setText("STH: " + String.valueOf(stealth));
        lblCardCunningCreated.setText("CNG: " + String.valueOf(cunning));


    }                                             

    private void txtCunningInputActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void txtStealthInputActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void txtSpeedInputActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void txtStrengthInputActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void txtCreateCardNameEntryActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    private void btnCreateCardActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        String[] getCreateCardData = {
            String.valueOf(name),
            String.valueOf(image),
            String.valueOf(strength),
            String.valueOf(speed),
            String.valueOf(stealth),
            String.valueOf(cunning),
        };
        
        System.out.println(Arrays.toString(getCreateCardData));
        
        
//        try {
//            FileWriter myWriter = new FileWriter("src/FileHandling/testFile.txt", true);
//            myWriter.write("helloooo");
//            myWriter.close();
//        } catch (IOException e) {
//            System.out.println(e);
//            e.printStackTrace();
//        }
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MonsterCardCatalogue().setVisible(true));
        

    }
    
        public void cardRender() {
            javax.swing.JLabel labelList[][] = {
                {lblCardImage1, lblCardName1, lblCardStrength1, lblCardSpeed1, lblCardStealth1, lblCardCunning1},
                {lblCardImage2, lblCardName2, lblCardStrength2, lblCardSpeed2, lblCardStealth2, lblCardCunning2},
                {lblCardImage3, lblCardName3, lblCardStrength3, lblCardSpeed3, lblCardStealth3, lblCardCunning3},
                {lblCardImage4, lblCardName4, lblCardStrength4, lblCardSpeed4, lblCardStealth4, lblCardCunning4},
                {lblCardImage5, lblCardName5, lblCardStrength5, lblCardSpeed5, lblCardStealth5, lblCardCunning5},
                {lblCardImage6, lblCardName6, lblCardStrength6, lblCardSpeed6, lblCardStealth6, lblCardCunning6},
                {lblCardImage7, lblCardName7, lblCardStrength7, lblCardSpeed7, lblCardStealth7, lblCardCunning7},
                {lblCardImage8, lblCardName8, lblCardStrength8, lblCardSpeed8, lblCardStealth8, lblCardCunning8},
                {lblCardImage9, lblCardName9, lblCardStrength9, lblCardSpeed9, lblCardStealth9, lblCardCunning9},
                {lblCardImage10, lblCardName10, lblCardStrength10, lblCardSpeed10, lblCardStealth10, lblCardCunning10},
            };
            
            for (int i = 0; i != 10; i = i + 1){
                for (int j = 0; j != 7; j = j + 1){
                    System.out.println(cardList[i][j]);
                    System.out.println(i + ", " + j);
                    labelList[i][0].setIcon(imageList[Integer.parseInt(cardList[i][1])]);
                    labelList[i][1].setText(cardList[i][0]);
                    labelList[i][2].setText("STR: " + cardList[i][2]);
                    labelList[i][3].setText("SPD: " + cardList[i][3]);
                    labelList[i][4].setText("STH: " + cardList[i][4]);
                    labelList[i][5].setText("CNG: " + cardList[i][5]);
                }
            }
            
        }
        
    
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCreateButton;
    private javax.swing.JButton btnCreateCard;
    private javax.swing.JButton btnDeleteButton;
    private javax.swing.JButton btnDiscardCard;
    private javax.swing.JButton btnQuitButton;
    private javax.swing.JButton btnQuitCreate;
    private javax.swing.JButton btnRenderCard;
    private javax.swing.JButton btnSearchButton;
    private javax.swing.JButton btnTextFileOutput;
    private javax.swing.JLabel lblCardCunning1;
    private javax.swing.JLabel lblCardCunning10;
    private javax.swing.JLabel lblCardCunning2;
    private javax.swing.JLabel lblCardCunning3;
    private javax.swing.JLabel lblCardCunning4;
    private javax.swing.JLabel lblCardCunning5;
    private javax.swing.JLabel lblCardCunning6;
    private javax.swing.JLabel lblCardCunning7;
    private javax.swing.JLabel lblCardCunning8;
    private javax.swing.JLabel lblCardCunning9;
    private javax.swing.JLabel lblCardCunningCreated;
    private javax.swing.JLabel lblCardImage1;
    private javax.swing.JLabel lblCardImage10;
    private javax.swing.JLabel lblCardImage2;
    private javax.swing.JLabel lblCardImage3;
    private javax.swing.JLabel lblCardImage4;
    private javax.swing.JLabel lblCardImage5;
    private javax.swing.JLabel lblCardImage6;
    private javax.swing.JLabel lblCardImage7;
    private javax.swing.JLabel lblCardImage8;
    private javax.swing.JLabel lblCardImage9;
    private javax.swing.JLabel lblCardImageCreated;
    private javax.swing.JLabel lblCardName1;
    private javax.swing.JLabel lblCardName10;
    private javax.swing.JLabel lblCardName2;
    private javax.swing.JLabel lblCardName3;
    private javax.swing.JLabel lblCardName4;
    private javax.swing.JLabel lblCardName5;
    private javax.swing.JLabel lblCardName6;
    private javax.swing.JLabel lblCardName7;
    private javax.swing.JLabel lblCardName8;
    private javax.swing.JLabel lblCardName9;
    private javax.swing.JLabel lblCardNameCreated;
    private javax.swing.JLabel lblCardSpeed1;
    private javax.swing.JLabel lblCardSpeed10;
    private javax.swing.JLabel lblCardSpeed2;
    private javax.swing.JLabel lblCardSpeed3;
    private javax.swing.JLabel lblCardSpeed4;
    private javax.swing.JLabel lblCardSpeed5;
    private javax.swing.JLabel lblCardSpeed6;
    private javax.swing.JLabel lblCardSpeed7;
    private javax.swing.JLabel lblCardSpeed8;
    private javax.swing.JLabel lblCardSpeed9;
    private javax.swing.JLabel lblCardSpeedCreated;
    private javax.swing.JLabel lblCardStealth1;
    private javax.swing.JLabel lblCardStealth10;
    private javax.swing.JLabel lblCardStealth2;
    private javax.swing.JLabel lblCardStealth3;
    private javax.swing.JLabel lblCardStealth4;
    private javax.swing.JLabel lblCardStealth5;
    private javax.swing.JLabel lblCardStealth6;
    private javax.swing.JLabel lblCardStealth7;
    private javax.swing.JLabel lblCardStealth8;
    private javax.swing.JLabel lblCardStealth9;
    private javax.swing.JLabel lblCardStealthCreated;
    private javax.swing.JLabel lblCardStrength1;
    private javax.swing.JLabel lblCardStrength10;
    private javax.swing.JLabel lblCardStrength2;
    private javax.swing.JLabel lblCardStrength3;
    private javax.swing.JLabel lblCardStrength4;
    private javax.swing.JLabel lblCardStrength5;
    private javax.swing.JLabel lblCardStrength6;
    private javax.swing.JLabel lblCardStrength7;
    private javax.swing.JLabel lblCardStrength8;
    private javax.swing.JLabel lblCardStrength9;
    private javax.swing.JLabel lblCardStrengthCreated;
    private javax.swing.JLabel lblCreateCard;
    private javax.swing.JLabel lblCreateTitle;
    private javax.swing.JLabel lblCunningValue;
    private javax.swing.JLabel lblImageToChoose;
    private javax.swing.JLabel lblSpeedValue;
    private javax.swing.JLabel lblStealthValue;
    private javax.swing.JLabel lblStrengthValue;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlCard1;
    private javax.swing.JPanel pnlCard10;
    private javax.swing.JPanel pnlCard2;
    private javax.swing.JPanel pnlCard3;
    private javax.swing.JPanel pnlCard4;
    private javax.swing.JPanel pnlCard5;
    private javax.swing.JPanel pnlCard6;
    private javax.swing.JPanel pnlCard7;
    private javax.swing.JPanel pnlCard8;
    private javax.swing.JPanel pnlCard9;
    private javax.swing.JPanel pnlCreatePanel;
    private javax.swing.JPanel pnlCreatedCard;
    private javax.swing.JPanel pnlHomePanel;
    private javax.swing.JPanel pnlParentPanel;
    private javax.swing.JTextField txtCreateCardNameEntry;
    private javax.swing.JTextField txtCunningInput;
    private javax.swing.JTextField txtImageInput;
    private javax.swing.JTextField txtSpeedInput;
    private javax.swing.JTextField txtStealthInput;
    private javax.swing.JTextField txtStrengthInput;
    // End of variables declaration                   
}
