/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eoy_project;

/**
 *
 * @author 23038
 */
public class MonsterCardCatalogue extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MonsterCardCatalogue.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public MonsterCardCatalogue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlParentPanel = new javax.swing.JPanel();
        pnlHomePanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnTextFileOutput = new javax.swing.JButton();
        btnQuitButton = new javax.swing.JButton();
        btnSearchButton = new javax.swing.JButton();
        btnCreateButton = new javax.swing.JButton();
        btnDeleteButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 231, 194));

        pnlParentPanel.setFocusTraversalPolicyProvider(true);
        pnlParentPanel.setLayout(new java.awt.CardLayout());

        pnlHomePanel.setBackground(new java.awt.Color(255, 231, 194));
        pnlHomePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 235, 153), 12));

        lblTitle.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        lblTitle.setText("Monster Card Catalogue");

        btnTextFileOutput.setBackground(new java.awt.Color(204, 163, 0));
        btnTextFileOutput.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btnTextFileOutput.setForeground(new java.awt.Color(255, 255, 255));
        btnTextFileOutput.setText("Text File Output");
        btnTextFileOutput.addActionListener(this::btnTextFileOutputActionPerformed);

        btnQuitButton.setBackground(new java.awt.Color(204, 0, 0));
        btnQuitButton.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnQuitButton.setForeground(new java.awt.Color(255, 255, 255));
        btnQuitButton.setText("Quit");
        btnQuitButton.addActionListener(this::btnQuitButtonActionPerformed);

        btnSearchButton.setBackground(new java.awt.Color(0, 37, 204));
        btnSearchButton.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnSearchButton.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchButton.setText("Search");
        btnSearchButton.addActionListener(this::btnSearchButtonActionPerformed);

        btnCreateButton.setBackground(new java.awt.Color(126, 217, 87));
        btnCreateButton.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnCreateButton.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateButton.setText("Create");
        btnCreateButton.addActionListener(this::btnCreateButtonActionPerformed);

        btnDeleteButton.setBackground(new java.awt.Color(255, 49, 49));
        btnDeleteButton.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnDeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteButton.setText("Delete");
        btnDeleteButton.addActionListener(this::btnDeleteButtonActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlHomePanelLayout = new javax.swing.GroupLayout(pnlHomePanel);
        pnlHomePanel.setLayout(pnlHomePanelLayout);
        pnlHomePanelLayout.setHorizontalGroup(
            pnlHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomePanelLayout.createSequentialGroup()
                .addGroup(pnlHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlHomePanelLayout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(btnCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(btnTextFileOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHomePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitle)))
                .addGap(236, 236, 236))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnQuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(340, 340, 340))
            .addGroup(pnlHomePanelLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHomePanelLayout.setVerticalGroup(
            pnlHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addGroup(pnlHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTextFileOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHomePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE))
        );

        pnlParentPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>                        

    private void btnTextFileOutputActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void btnQuitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void btnSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void btnCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void btnDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MonsterCardCatalogue().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCreateButton;
    private javax.swing.JButton btnDeleteButton;
    private javax.swing.JButton btnQuitButton;
    private javax.swing.JButton btnSearchButton;
    private javax.swing.JButton btnTextFileOutput;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlHomePanel;
    private javax.swing.JPanel pnlParentPanel;
    // End of variables declaration                   
}
